version: 2.1

jobs:
  install:
    docker: &BUILDIMAGE
      - image: jenkinsrise/cci-v2-components:0.0.5
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test:
    docker: *BUILDIMAGE
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: npm test

  build:
    docker: *BUILDIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: |
          VERSION=$(cat version-string/version)
          sed -i "
            s/__VERSION__/$VERSION/;
          " src/rise-image-version.js
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  gcloud-setup:
    docker: &GCSIMAGE
      - image: jenkinsrise/cci-v2-launcher-electron:0.0.6
        environment:
          COMPONENT_NAME: rise-image
          WIDGETS_BASE: gs://widgets.risevision.com
    steps:
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run: mv private-keys ..
      - run: gcloud auth activate-service-account 452091732215@developer.gserviceaccount.com --key-file ../private-keys/storage-server/rva-media-library-ce0d2bd78b54.json
      - persist_to_workspace:
          root: ~/.config
          paths:
            - gcloud

  generate-version:
    docker: *BUILDIMAGE
    steps:
      - run: mkdir version-string
      - run: echo $(date +%Y.%m.%d.%H.%M) > version-string/version
      - persist_to_workspace:
          root: .
          paths:
            - version-string

  build-e2e-page:
    parameters:
      stage:
        type: string
    docker: *BUILDIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: echo build e2e page << parameters.stage >>
      - run: |
          VERSION=$(cat version-string/version)
          sed "
            s/__STAGE__/<< parameters.stage >>/;
            s/__VERSION__/$VERSION/;
          " e2e/rise-image.html > e2e/rise-image-electron.html
      - run: cp e2e/polymer-e2e-electron.json polymer.json
      - run: polymer build
      - persist_to_workspace:
          root: ./build
          paths:
            - base

  deploy-stage:
    docker: *GCSIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: mkdir -p ~/.config
      - run: cp -r gcloud ~/.config
      - run: |
          VERSION=$(cat version-string/version)
          TARGET=$WIDGETS_BASE/staging/components/$COMPONENT_NAME/$VERSION/
          echo Deploying version $VERSION to $COMPONENT_NAME
          node_modules/common-component/deploy-gcs.sh $COMPONENT_NAME $TARGET

  deploy-production:
    parameters:
      stage:
        type: string
    docker: *GCSIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: mkdir -p ~/.config
      - run: cp -r gcloud ~/.config
      - run: |
          TARGET=$WIDGETS_BASE/<< parameters.stage >>/components/$COMPONENT_NAME/
          echo Deploying << parameters.stage >> version of $COMPONENT_NAME
          node_modules/common-component/deploy-gcs.sh $COMPONENT_NAME $TARGET

workflows:
  workflow1:
    jobs:
      - install
      - gcloud-setup:
          filters:
            branches:
              only:
                - /^(stage|staging)[/].*/
                - /^e2e[/].*/
                - master
                - build/stable
      - generate-version:
          filters:
            branches:
              only:
                - /^(stage|staging)[/].*/
                - /^e2e[/].*/
                - master
                - build/stable
      - test:
          requires:
            - install
      - build:
          requires:
            - test
            - generate-version
          filters:
            branches:
              only:
                - /^(stage|staging)[/].*/
                - /^e2e[/].*/
                - master
                - build/stable
      - build-e2e-page:
          stage: beta
          name: build-e2e-page-beta
          requires:
            - build
          filters:
            branches:
              only:
                - /^e2e[/].*/
                - master
      - build-e2e-page:
          stage: stable
          name: build-e2e-page-stable
          requires:
            - build
          filters:
            branches:
              only:
                - build/stable
      - deploy-stage:
          requires:
            - gcloud-setup
            - build
          filters:
            branches:
              only:
                - /^(stage|staging)[/].*/
                - /^e2e[/].*/
                - master
                - build/stable
      - deploy-production:
          stage: beta
          name: deploy-beta
          requires:
            - deploy-stage
          filters:
            branches:
              only:
                - master
      - deploy-production:
          stage: stable
          name: deploy-stable
          requires:
            - deploy-stage
          filters:
            branches:
              only:
                - build/stable
